BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `kcal_table` (
	`food`	TEXT,
	`kcal`	INTEGER
);
INSERT INTO `kcal_table` VALUES ('cereal',350);
INSERT INTO `kcal_table` VALUES ('baekseolgi',234);
INSERT INTO `kcal_table` VALUES ('songqyeon',40);
INSERT INTO `kcal_table` VALUES ('injeolmi',80);
INSERT INTO `kcal_table` VALUES ('steamed potato',109);
INSERT INTO `kcal_table` VALUES ('steamed sweetpotato',250);
INSERT INTO `kcal_table` VALUES ('kimchi stew',157);
INSERT INTO `kcal_table` VALUES ('doenjang stew',160);
INSERT INTO `kcal_table` VALUES ('egg soup',55);
INSERT INTO `kcal_table` VALUES ('dumpling soup',400);
INSERT INTO `kcal_table` VALUES ('tteokguk',420);
INSERT INTO `kcal_table` VALUES ('sea mustard soup',50);
INSERT INTO `kcal_table` VALUES ('sausage stew',256);
INSERT INTO `kcal_table` VALUES ('seolleongtang',240);
INSERT INTO `kcal_table` VALUES ('beef radish soup',110);
INSERT INTO `kcal_table` VALUES ('soft tofu stew',240);
INSERT INTO `kcal_table` VALUES ('yukgaejang',240);
INSERT INTO `kcal_table` VALUES ('bean sprouts soup',43);
INSERT INTO `kcal_table` VALUES ('braised cutlassfish',125);
INSERT INTO `kcal_table` VALUES ('braised mackerel',200);
INSERT INTO `kcal_table` VALUES ('mapa tofu',125);
INSERT INTO `kcal_table` VALUES ('beef jangjorim',125);
INSERT INTO `kcal_table` VALUES ('fried kimchi',100);
INSERT INTO `kcal_table` VALUES ('fried octopus',125);
INSERT INTO `kcal_table` VALUES ('fired anchovies',100);
INSERT INTO `kcal_table` VALUES ('fried sausage',175);
INSERT INTO `kcal_table` VALUES ('fried squid',150);
INSERT INTO `kcal_table` VALUES ('japchae',175);
INSERT INTO `kcal_table` VALUES ('fried spicy pork',225);
INSERT INTO `kcal_table` VALUES ('grilled cutlassfish',100);
INSERT INTO `kcal_table` VALUES ('grilled saury',175);
INSERT INTO `kcal_table` VALUES ('grilled spareribs',225);
INSERT INTO `kcal_table` VALUES ('bacon',200);
INSERT INTO `kcal_table` VALUES ('grilled mackerel',150);
INSERT INTO `kcal_table` VALUES ('grilled croaker',100);
INSERT INTO `kcal_table` VALUES ('potato pancakes',150);
INSERT INTO `kcal_table` VALUES ('fried eggs',100);
INSERT INTO `kcal_table` VALUES ('pajeon',100);
INSERT INTO `kcal_table` VALUES ('fried potato',125);
INSERT INTO `kcal_table` VALUES ('bulgogi',50);
INSERT INTO `kcal_table` VALUES ('mung bean pancake',200);
INSERT INTO `kcal_table` VALUES ('pumpkin pancake',100);
INSERT INTO `kcal_table` VALUES ('pork cutlet',225);
INSERT INTO `kcal_table` VALUES ('fried chicken',175);
INSERT INTO `kcal_table` VALUES ('fried shrimp',150);
INSERT INTO `kcal_table` VALUES ('fried squid',175);
INSERT INTO `kcal_table` VALUES ('kkakdugi',25);
INSERT INTO `kcal_table` VALUES ('cabbage kimchi',11);
INSERT INTO `kcal_table` VALUES ('pickled radish',2);
INSERT INTO `kcal_table` VALUES ('pickle',21);
INSERT INTO `kcal_table` VALUES ('shrimp sushi',56);
INSERT INTO `kcal_table` VALUES ('fish cake',100);
INSERT INTO `kcal_table` VALUES ('udon',470);
INSERT INTO `kcal_table` VALUES ('tofu sushi',570);
INSERT INTO `kcal_table` VALUES ('fried dumpling',315);
INSERT INTO `kcal_table` VALUES ('jajangmyeon',537);
INSERT INTO `kcal_table` VALUES ('jjamppong',510);
INSERT INTO `kcal_table` VALUES ('chicken doria',979);
INSERT INTO `kcal_table` VALUES ('curry',580);
INSERT INTO `kcal_table` VALUES ('pizza',250);
INSERT INTO `kcal_table` VALUES ('soda',100);
INSERT INTO `kcal_table` VALUES ('sikhye',208);
INSERT INTO `kcal_table` VALUES ('coke',89);
INSERT INTO `kcal_table` VALUES ('fanta',120);
INSERT INTO `kcal_table` VALUES ('milk coffee',42);
INSERT INTO `kcal_table` VALUES ('black coffee',5);
INSERT INTO `kcal_table` VALUES ('green tea',17);
INSERT INTO `kcal_table` VALUES ('lemon tea',59);
INSERT INTO `kcal_table` VALUES ('tea',4);
INSERT INTO `kcal_table` VALUES ('soya milk',130);
INSERT INTO `kcal_table` VALUES ('strawberry milk',180);
INSERT INTO `kcal_table` VALUES ('banana milk',175);
INSERT INTO `kcal_table` VALUES ('milk',120);
INSERT INTO `kcal_table` VALUES ('chocolate milk',126);
INSERT INTO `kcal_table` VALUES ('coffee milk',126);
INSERT INTO `kcal_table` VALUES ('chocolate',260);
INSERT INTO `kcal_table` VALUES ('popcorn',109);
INSERT INTO `kcal_table` VALUES ('butter ring',430);
INSERT INTO `kcal_table` VALUES ('sun chip',402);
INSERT INTO `kcal_table` VALUES ('ace',810);
INSERT INTO `kcal_table` VALUES ('potato chip',330);
INSERT INTO `kcal_table` VALUES ('mandarin',19);
INSERT INTO `kcal_table` VALUES ('grapefruit',95);
INSERT INTO `kcal_table` VALUES ('kiwi',54);
INSERT INTO `kcal_table` VALUES ('strawberry',52);
INSERT INTO `kcal_table` VALUES ('banana',93);
INSERT INTO `kcal_table` VALUES ('apple',98);
INSERT INTO `kcal_table` VALUES ('tomato',17);
INSERT INTO `kcal_table` VALUES ('water melon',30);
INSERT INTO `kcal_table` VALUES ('oriental melon',30);
INSERT INTO `kcal_table` VALUES ('pineapple',11);
INSERT INTO `kcal_table` VALUES ('melon',19);
INSERT INTO `kcal_table` VALUES ('peach',91);
INSERT INTO `kcal_table` VALUES ('orange',131);
INSERT INTO `kcal_table` VALUES ('grape',90);
INSERT INTO `kcal_table` VALUES ('gimbap',475);
INSERT INTO `kcal_table` VALUES ('bibimbap',525);
INSERT INTO `kcal_table` VALUES ('meat dumpling',270);
INSERT INTO `kcal_table` VALUES ('spicy noodle',535);
INSERT INTO `kcal_table` VALUES ('kalguksu',500);
INSERT INTO `kcal_table` VALUES ('kimchi fried rice',450);
INSERT INTO `kcal_table` VALUES ('tteokbokki',480);
INSERT INTO `kcal_table` VALUES ('sundae',520);
INSERT INTO `kcal_table` VALUES ('mulnaengmyeon',450);
INSERT INTO `kcal_table` VALUES ('bibimnaengmyeon',500);
INSERT INTO `kcal_table` VALUES ('bean noodle',515);
INSERT INTO `kcal_table` VALUES ('soju',71);
INSERT INTO `kcal_table` VALUES ('makgeolli',110);
INSERT INTO `kcal_table` VALUES ('whiskey',140);
INSERT INTO `kcal_table` VALUES ('beer',86);
INSERT INTO `kcal_table` VALUES ('wine',110);
INSERT INTO `kcal_table` VALUES ('bread',50);
INSERT INTO `kcal_table` VALUES ('baguette',768);
INSERT INTO `kcal_table` VALUES ('custard cream',195);
INSERT INTO `kcal_table` VALUES ('red bean bread',234);
INSERT INTO `kcal_table` VALUES ('cheese cake',300);
INSERT INTO `kcal_table` VALUES ('boiled egg',100);
INSERT INTO `kcal_table` VALUES ('yukhoe',100);
INSERT INTO `kcal_table` VALUES ('pig feet',200);
INSERT INTO `kcal_table` VALUES ('ramen',500);
INSERT INTO `kcal_table` VALUES ('salad',150);
COMMIT;
